//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

pub use super::alert_notification::Entity as AlertNotification;
pub use super::chain::Entity as Chain;
pub use super::crawler::Entity as Crawler;
pub use super::jwt::Entity as Jwt;
pub use super::telegram_chat_id::Entity as TelegramChatId;
pub use super::user_alert::Entity as UserAlert;
