//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "processed_blocks")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub chain_id: i32,
    pub last_processed_block: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::chain::Entity",
        from = "Column::ChainId",
        to = "super::chain::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Chain,
}

impl Related<super::chain::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Chain.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
