//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user_alert")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub user_id: String,
    pub chain_id: i32,
    pub alert: String,
    pub message: String,
    pub status: i32,
    pub alert_source: i32,
    pub name: String,
    pub created_at: String,
    pub updated_at: String,
    pub deleted_at: Option<String>,
    pub client_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::alert_notification::Entity")]
    AlertNotification,
    #[sea_orm(
        belongs_to = "super::chain::Entity",
        from = "Column::ChainId",
        to = "super::chain::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Chain,
}

impl Related<super::alert_notification::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AlertNotification.def()
    }
}

impl Related<super::chain::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Chain.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
